use std::collections::BTreeMap;

use serde::Deserialize;

use crate::{Lockfile, LockfileError, Package};

#[derive(Debug, Clone, PartialEq, Eq)]
struct YarnBerryEntry {
    version: String,
    dependencies: BTreeMap<String, String>,
}

#[derive(Debug, Clone, Deserialize, PartialEq, Eq)]
struct YarnBerryMetadata {
    version: u64,
    #[serde(rename = "cacheKey")]
    cache_key: serde_norway::Value,
}

#[derive(Debug, Clone, Deserialize, PartialEq, Eq)]
struct YarnBerryRawEntry {
    version: String,
    #[serde(default)]
    dependencies: BTreeMap<String, String>,
}

#[derive(Debug, Clone, Default)]
pub struct YarnBerryLockfile {
    entries_by_descriptor: BTreeMap<String, YarnBerryEntry>,
}

impl YarnBerryLockfile {
    pub fn parse(content: &str) -> Result<Self, LockfileError> {
        let document = serde_norway::from_str::<serde_norway::Mapping>(content)
            .map_err(|error| LockfileError::Parse(error.to_string()))?;

        let metadata_value = document
            .get(serde_norway::Value::String("__metadata".to_string()))
            .ok_or_else(|| LockfileError::Parse("missing __metadata block".to_string()))?
            .clone();
        let _: YarnBerryMetadata = serde_norway::from_value(metadata_value)
            .map_err(|error| LockfileError::Parse(error.to_string()))?;

        let mut entries_by_descriptor = BTreeMap::new();

        for (key, value) in document {
            let serde_norway::Value::String(key) = key else {
                return Err(LockfileError::Parse(
                    "unexpected non-string key in Yarn Berry lockfile".to_string(),
                ));
            };

            if key == "__metadata" {
                continue;
            }

            let entry: YarnBerryRawEntry = serde_norway::from_value(value)
                .map_err(|error| LockfileError::Parse(error.to_string()))?;
            let normalized_entry = YarnBerryEntry {
                version: entry.version,
                dependencies: entry.dependencies,
            };

            for descriptor in key.split(", ") {
                entries_by_descriptor.insert(descriptor.to_string(), normalized_entry.clone());
            }
        }

        Ok(Self {
            entries_by_descriptor,
        })
    }

    fn candidate_keys(name: &str, version: &str) -> Vec<String> {
        let mut candidates = Vec::with_capacity(2);

        if version.contains(':') {
            candidates.push(format!("{name}@{version}"));
        } else {
            candidates.push(format!("{name}@npm:{version}"));
            candidates.push(format!("{name}@{version}"));
        }

        candidates
    }
}

impl Lockfile for YarnBerryLockfile {
    fn resolve_package(
        &self,
        _workspace_path: &str,
        name: &str,
        version: &str,
    ) -> Result<Option<Package>, LockfileError> {
        Ok(Self::candidate_keys(name, version)
            .into_iter()
            .find_map(|key| {
                self.entries_by_descriptor
                    .get(&key)
                    .map(|entry| Package::new(key, entry.version.clone()))
            }))
    }

    /// Returns dependency map with raw Berry range strings intact, including
    /// protocol prefixes such as `npm:`. That preserves round-tripping because
    /// each returned value can be passed back into `resolve_package` directly.
    fn all_dependencies(&self, key: &str) -> Result<BTreeMap<String, String>, LockfileError> {
        self.entries_by_descriptor
            .get(key)
            .map(|entry| entry.dependencies.clone())
            .ok_or_else(|| LockfileError::InvalidPackageReference(key.to_string()))
    }
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use super::*;
    use crate::parse_lockfile;

    const FIXTURE: &str = r#"__metadata:
  version: 8
  cacheKey: 10

"chalk@npm:^4.1.2":
  version: 4.1.2
  resolution: "chalk@npm:4.1.2"
  dependencies:
    ansi-styles: "npm:^4.1.0"
    supports-color: "npm:^7.1.0"
  checksum: 10/abc123
  languageName: node
  linkType: hard

"@babel/core@npm:^7.0.0, @babel/core@npm:^7.22.0":
  version: 7.23.0
  resolution: "@babel/core@npm:7.23.0"
  dependencies:
    "@babel/types": "npm:^7.23.0"
  languageName: node
  linkType: hard

"my-app@workspace:.":
  version: 0.0.0-use.local
  resolution: "my-app@workspace:."
  dependencies:
    chalk: "npm:^4.1.2"
  languageName: node
  linkType: soft
"#;

    const YARN1_FIXTURE: &str = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

chalk@^4.1.2:
  version "4.1.2"
  resolved "https://registry.yarnpkg.com/chalk/-/chalk-4.1.2.tgz#aac4e2b7734a740867aeb16bf02aad556a1e7a01"
  integrity sha512-oKnbhFyRIXAVdJ5D5dQvDFi1Cdm42Hcps225y7sY9qsK0kGugHgdGXN53BJ38qRAjPR9U1FVLtZL1NVr7Di5LA==
"#;

    #[test]
    fn parses_realistic_yarn_berry_fixture() {
        let lockfile = YarnBerryLockfile::parse(FIXTURE).expect("fixture should parse");

        assert!(lockfile
            .entries_by_descriptor
            .contains_key("chalk@npm:^4.1.2"));
        assert!(lockfile
            .entries_by_descriptor
            .contains_key("@babel/core@npm:^7.0.0"));
        assert!(lockfile
            .entries_by_descriptor
            .contains_key("@babel/core@npm:^7.22.0"));
    }

    #[test]
    fn resolves_known_package() {
        let lockfile = YarnBerryLockfile::parse(FIXTURE).expect("fixture should parse");

        let package = lockfile
            .resolve_package("packages/app", "chalk", "^4.1.2")
            .expect("resolution should succeed")
            .expect("package should exist");

        assert_eq!(package.key, "chalk@npm:^4.1.2");
        assert_eq!(package.version, "4.1.2");
    }

    #[test]
    fn resolves_scoped_package() {
        let lockfile = YarnBerryLockfile::parse(FIXTURE).expect("fixture should parse");

        let package = lockfile
            .resolve_package("packages/app", "@babel/core", "^7.0.0")
            .expect("resolution should succeed")
            .expect("package should exist");

        assert_eq!(package.key, "@babel/core@npm:^7.0.0");
        assert_eq!(package.version, "7.23.0");
    }

    #[test]
    fn resolves_descriptor_from_joined_key() {
        let lockfile = YarnBerryLockfile::parse(FIXTURE).expect("fixture should parse");

        let package = lockfile
            .resolve_package("packages/app", "@babel/core", "^7.22.0")
            .expect("resolution should succeed")
            .expect("package should exist");

        assert_eq!(package.key, "@babel/core@npm:^7.22.0");
        assert_eq!(package.version, "7.23.0");
    }

    #[test]
    fn returns_direct_dependencies_for_entry() {
        let lockfile = YarnBerryLockfile::parse(FIXTURE).expect("fixture should parse");

        let dependencies = lockfile
            .all_dependencies("chalk@npm:^4.1.2")
            .expect("dependency lookup should succeed");

        assert_eq!(
            dependencies,
            BTreeMap::from([
                ("ansi-styles".to_string(), "npm:^4.1.0".to_string()),
                ("supports-color".to_string(), "npm:^7.1.0".to_string()),
            ])
        );
    }

    #[test]
    fn missing_package_returns_none() {
        let lockfile = YarnBerryLockfile::parse(FIXTURE).expect("fixture should parse");

        let package = lockfile
            .resolve_package("packages/app", "react", "^18.2.0")
            .expect("resolution should succeed");

        assert!(package.is_none());
    }

    #[test]
    fn parse_errors_when_metadata_block_is_missing() {
        let err = YarnBerryLockfile::parse(
            r#""chalk@npm:^4.1.2":
  version: 4.1.2
  resolution: "chalk@npm:4.1.2"
"#,
        )
        .expect_err("parse should fail");

        assert!(matches!(err, LockfileError::Parse(_)));
    }

    #[test]
    fn parse_errors_when_metadata_is_malformed() {
        let err = YarnBerryLockfile::parse(
            r#"__metadata:
  version: nope

"chalk@npm:^4.1.2":
  version: 4.1.2
"#,
        )
        .expect_err("parse should fail");

        assert!(matches!(err, LockfileError::Parse(_)));
    }

    #[test]
    fn parse_errors_when_entry_schema_is_invalid() {
        let err = YarnBerryLockfile::parse(
            r#"__metadata:
  version: 8
  cacheKey: 10

"chalk@npm:^4.1.2":
  resolution: "chalk@npm:4.1.2"
"#,
        )
        .expect_err("parse should fail");

        assert!(matches!(err, LockfileError::Parse(_)));
    }

    #[test]
    fn parse_errors_when_content_is_not_yaml() {
        let err = YarnBerryLockfile::parse(YARN1_FIXTURE).expect_err("parse should fail");

        assert!(matches!(err, LockfileError::Parse(_)));
    }

    #[test]
    fn all_dependencies_errors_for_unknown_key() {
        let lockfile = YarnBerryLockfile::parse(FIXTURE).expect("fixture should parse");

        let err = lockfile
            .all_dependencies("does-not-exist@npm:^1.0.0")
            .expect_err("lookup should fail");

        assert!(matches!(err, LockfileError::InvalidPackageReference(_)));
    }

    #[test]
    fn parse_lockfile_auto_detects_berry_fixture() {
        let lockfile = parse_lockfile(FIXTURE).expect("fixture should parse");

        let package = lockfile
            .resolve_package("packages/app", "chalk", "^4.1.2")
            .expect("resolution should succeed")
            .expect("package should exist");

        assert_eq!(package.version, "4.1.2");
    }

    #[test]
    fn parse_lockfile_auto_detects_yarn_v1_fixture() {
        let lockfile = parse_lockfile(YARN1_FIXTURE).expect("fixture should parse");

        let package = lockfile
            .resolve_package("packages/app", "chalk", "^4.1.2")
            .expect("resolution should succeed")
            .expect("package should exist");

        assert_eq!(package.version, "4.1.2");
        assert_eq!(package.key, "chalk@^4.1.2");
    }
}
