use std::collections::BTreeMap;

use yarn_lock_parser::parse_str;

use crate::{Lockfile, LockfileError, Package};

#[derive(Debug, Clone, PartialEq, Eq)]
struct Yarn1Entry {
    name: String,
    version: String,
    dependencies: BTreeMap<String, String>,
}

/// Yarn v1 lockfile parser.
///
/// `Package.key` uses descriptor form `name@range`, matching one descriptor from
/// parsed `yarn.lock` entry. That key is stable enough to look entry back up for
/// `all_dependencies`.
#[derive(Debug, Clone, Default)]
pub struct Yarn1Lockfile {
    entries_by_key: BTreeMap<String, Yarn1Entry>,
}

impl Yarn1Lockfile {
    /// Creates parsed Yarn v1 lockfile from file contents.
    pub fn parse(content: &str) -> Result<Self, LockfileError> {
        let parsed = parse_str(content).map_err(|error| LockfileError::Parse(error.to_string()))?;
        let mut entries_by_key = BTreeMap::new();

        for entry in parsed.entries {
            let dependencies = entry
                .dependencies
                .into_iter()
                .map(|(name, version)| (name.to_string(), version.to_string()))
                .collect::<BTreeMap<_, _>>();

            for (descriptor_name, descriptor_range) in entry.descriptors {
                let key = format!("{descriptor_name}@{descriptor_range}");
                entries_by_key.insert(
                    key,
                    Yarn1Entry {
                        name: entry.name.to_string(),
                        version: entry.version.to_string(),
                        dependencies: dependencies.clone(),
                    },
                );
            }
        }

        Ok(Self { entries_by_key })
    }
}

impl Lockfile for Yarn1Lockfile {
    fn resolve_package(
        &self,
        _workspace_path: &str,
        name: &str,
        version: &str,
    ) -> Result<Option<Package>, LockfileError> {
        let key = format!("{name}@{version}");
        Ok(self
            .entries_by_key
            .get(&key)
            .map(|entry| Package::new(key, entry.version.clone())))
    }

    fn all_dependencies(&self, key: &str) -> Result<BTreeMap<String, String>, LockfileError> {
        self.entries_by_key
            .get(key)
            .map(|entry| entry.dependencies.clone())
            .ok_or_else(|| LockfileError::InvalidPackageReference(key.to_string()))
    }
}

#[cfg(test)]
mod tests {
    use std::collections::{BTreeMap, BTreeSet};

    use super::*;

    const FIXTURE: &str = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

left-pad@^1.3.0:
  version "1.3.0"
  resolved "https://registry.yarnpkg.com/left-pad/-/left-pad-1.3.0.tgz#5b8a3a7765dfe001261dde915589e782f8c94d1e"
  integrity sha512-XI5MPzVNApjAyhQzZWn7Q4oJ4kBzP4Qzy6wKzH8w0v7lidh+NROm4tW7x1YgnPZXoqBYwygJyI072QtdgQXl3g==

lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#679591c564c3bffaae8454cf0b3df370c3d6911c"
  integrity sha512-v2kDEe57lecTuJQkz59wW2j6xL8GZFODdgNpTi27C/medhOiabuX41sJLdnOjFkWDXLI4YAlnXrhIRbkIuWGHQ==

chalk@^4.1.2:
  version "4.1.2"
  resolved "https://registry.yarnpkg.com/chalk/-/chalk-4.1.2.tgz#aac4e2b7734a740867aeb16bf02aad556a1e7a01"
  integrity sha512-oKnbhFyRIXAVdJ5D5dQvDFi1Cdm42Hcps225y7sY9qsK0kGugHgdGXN53BJ38qRAjPR9U1FVLtZL1NVr7Di5LA==
  dependencies:
    ansi-styles "^4.1.0"
    supports-color "^7.1.0"

ansi-styles@^4.1.0:
  version "4.3.0"
  resolved "https://registry.yarnpkg.com/ansi-styles/-/ansi-styles-4.3.0.tgz#edd803628ae71c04c85ae7a0906edad34b648937"
  integrity sha512-zbB9rCJAT1KhGsa1+lZeXqIuAv89xDSHLVbkP4Jrped1IovnHgwlHGawEq+y3OCAXoTr4Wr9L5xRngkQCk2B9g==
  dependencies:
    color-convert "^2.0.1"

supports-color@^7.1.0:
  version "7.2.0"
  resolved "https://registry.yarnpkg.com/supports-color/-/supports-color-7.2.0.tgz#1b7dcdcb32b8138801b3e478ba6a51caa89648da"
  integrity sha512-qpCAvRl9eA9H9n1tFoZT3zh0+BTtPlqvGjufH6G+jD/adJzi10BGSAdoo6gWQBaIj++ImQxGc1dQc5sKXc5teQ==
  dependencies:
    has-flag "^4.0.0"
"#;

    #[test]
    fn parses_realistic_yarn_v1_fixture() {
        let lockfile = Yarn1Lockfile::parse(FIXTURE).expect("fixture should parse");

        assert!(lockfile.entries_by_key.contains_key("chalk@^4.1.2"));
        assert!(lockfile.entries_by_key.contains_key("left-pad@^1.3.0"));
    }

    #[test]
    fn resolves_known_package() {
        let lockfile = Yarn1Lockfile::parse(FIXTURE).expect("fixture should parse");

        let package = lockfile
            .resolve_package("packages/app", "chalk", "^4.1.2")
            .expect("resolution should succeed")
            .expect("package should exist");

        assert_eq!(package.key, "chalk@^4.1.2");
        assert_eq!(package.version, "4.1.2");
    }

    #[test]
    fn returns_direct_dependencies_for_entry() {
        let lockfile = Yarn1Lockfile::parse(FIXTURE).expect("fixture should parse");

        let dependencies = lockfile
            .all_dependencies("chalk@^4.1.2")
            .expect("dependency lookup should succeed");

        assert_eq!(
            dependencies,
            BTreeMap::from([
                ("ansi-styles".to_string(), "^4.1.0".to_string()),
                ("supports-color".to_string(), "^7.1.0".to_string()),
            ])
        );
    }

    #[test]
    fn missing_package_returns_none() {
        let lockfile = Yarn1Lockfile::parse(FIXTURE).expect("fixture should parse");

        let package = lockfile
            .resolve_package("packages/app", "react", "^18.2.0")
            .expect("resolution should succeed");

        assert!(package.is_none());
    }

    // Fixture for transitive dependency chain: A -> B -> C
    const TRANSITIVE_FIXTURE: &str = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

package-a@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/package-a/-/package-a-1.0.0.tgz#aaa"
  dependencies:
    package-b "^2.0.0"

package-b@^2.0.0:
  version "2.0.0"
  resolved "https://registry.yarnpkg.com/package-b/-/package-b-2.0.0.tgz#bbb"
  dependencies:
    package-c "^3.0.0"

package-c@^3.0.0:
  version "3.0.0"
  resolved "https://registry.yarnpkg.com/package-c/-/package-c-3.0.0.tgz#ccc"
"#;

    #[test]
    fn transitive_dependencies_returns_full_closure() {
        let lockfile = Yarn1Lockfile::parse(TRANSITIVE_FIXTURE).expect("fixture should parse");

        let deps = lockfile
            .transitive_dependencies("package-a@^1.0.0")
            .expect("transitive lookup should succeed");

        assert_eq!(
            deps,
            BTreeSet::from([
                ("package-b".to_string(), "2.0.0".to_string()),
                ("package-c".to_string(), "3.0.0".to_string()),
            ])
        );
    }

    // Fixture for cycle detection: A -> B -> A
    const CYCLE_FIXTURE: &str = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

package-a@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/package-a/-/package-a-1.0.0.tgz#aaa"
  dependencies:
    package-b "^2.0.0"

package-b@^2.0.0:
  version "2.0.0"
  resolved "https://registry.yarnpkg.com/package-b/-/package-b-2.0.0.tgz#bbb"
  dependencies:
    package-a "^1.0.0"
"#;

    #[test]
    fn transitive_dependencies_handles_cycle() {
        let lockfile = Yarn1Lockfile::parse(CYCLE_FIXTURE).expect("fixture should parse");

        let deps = lockfile
            .transitive_dependencies("package-a@^1.0.0")
            .expect("transitive lookup should succeed");

        assert_eq!(
            deps,
            BTreeSet::from([
                ("package-a".to_string(), "1.0.0".to_string()),
                ("package-b".to_string(), "2.0.0".to_string()),
            ])
        );
    }

    const DUPLICATE_NAME_FIXTURE: &str = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

package-a@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/package-a/-/package-a-1.0.0.tgz#aaa"
  dependencies:
    package-b "^2.0.0"
    package-c "^3.0.0"

package-b@^2.0.0:
  version "2.0.0"
  resolved "https://registry.yarnpkg.com/package-b/-/package-b-2.0.0.tgz#bbb"
  dependencies:
    shared-dep "^1.0.0"

package-c@^3.0.0:
  version "3.0.0"
  resolved "https://registry.yarnpkg.com/package-c/-/package-c-3.0.0.tgz#ccc"
  dependencies:
    shared-dep "^2.0.0"

shared-dep@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/shared-dep/-/shared-dep-1.0.0.tgz#ddd"

shared-dep@^2.0.0:
  version "2.0.0"
  resolved "https://registry.yarnpkg.com/shared-dep/-/shared-dep-2.0.0.tgz#eee"
"#;

    #[test]
    fn transitive_dependencies_retains_multiple_versions_of_same_name() {
        let lockfile = Yarn1Lockfile::parse(DUPLICATE_NAME_FIXTURE).expect("fixture should parse");

        let deps = lockfile
            .transitive_dependencies("package-a@^1.0.0")
            .expect("transitive lookup should succeed");

        assert!(deps.contains(&("shared-dep".to_string(), "1.0.0".to_string())));
        assert!(deps.contains(&("shared-dep".to_string(), "2.0.0".to_string())));
    }

    #[test]
    fn transitive_dependencies_deterministic() {
        let lockfile = Yarn1Lockfile::parse(TRANSITIVE_FIXTURE).expect("fixture should parse");

        let deps1 = lockfile
            .transitive_dependencies("package-a@^1.0.0")
            .expect("transitive lookup should succeed");
        let deps2 = lockfile
            .transitive_dependencies("package-a@^1.0.0")
            .expect("transitive lookup should succeed");

        assert_eq!(deps1, deps2);
    }
}
