[package]
name = "luchta-yarn-worker"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true

[dependencies]
luchta-worker = { path = "../luchta-worker" }
luchta-yarn-env = { path = "../luchta-yarn-env" }
tokio = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
luchta-engine = { path = "../luchta-engine" }
luchta-yarn-env = { path = "../luchta-yarn-env", features = ["test-fixture"] }
serde_json = { workspace = true }
tempfile = { workspace = true }
