nextest-version = "0.9.99"
experimental = ["wrapper-scripts"]

[scripts.wrapper.hermetic-unix]
command = { command-line = "scripts/nextest-hermetic.sh", relative-to = "workspace-root" }
target-runner = "within-wrapper"

[scripts.wrapper.hermetic-windows]
command = { command-line = "scripts/nextest-hermetic.cmd", relative-to = "workspace-root" }
target-runner = "within-wrapper"

[[profile.default.scripts]]
filter = "all()"
platform = { host = "cfg(unix)" }
run-wrapper = "hermetic-unix"

[[profile.default.scripts]]
filter = "all()"
platform = { host = "cfg(windows)" }
run-wrapper = "hermetic-windows"
